apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/imammaulanaa/blue-green-deployment.git'
    targetRevision: HEAD
    path: app/overlays/blue
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
